version: "3.9"

services:
  dev:
    image: $DOCKER_USERNAME/azure-infrastructure-as-code-starter:latest
    ports:
      - "8080:5000"
    env_file:
      - ./.env
    command: ["gunicorn", "--bind", "0.0.0.0:5000", "wsgi"]
