version: "3.9"

services:
  dev:
    image: $DOCKER_USERNAME/azure-infrastructure-as-code-starter:latest
    expose:
      - 80
    ports:
      - "8080:80"
    env_file:
      - ./.env
    command: ["gunicorn", "--bind", "0.0.0.0:8080", "wsgi"]
