version: "3.9"

services:
  app:
    build: ./app
    volumes:
      - ./app/flaskapp:/app
      - socket:/tmp
    command: uwsgi --ini /app/app.ini

  nginx:
    image: nginx:stable-alpine
    ports:
      - "8000:80"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - socket:/tmp

volumes:
  socket:
