version: "3.9"

services:
  dev:
    image: $DOCKER_USERNAME/azure-docker-react-advanced-dev:latest
    expose: "80"
    ports:
      - "8080:80"
    command: ["gunicorn", "--debug", "--bind", "0.0.0.0:8080", "wsgi"]
