version: "3.9"

services:
  web:
    build: .
    image: $DOCKER_USERNAME/azure-infrastructure-as-code-starter:latest
    command: ["gunicorn", "--bind", "0.0.0.0:$WEBSITES_PORT", "wsgi"]
    ports:
      - "8000:$WEBSITES_PORT"
    # expose:
    #   - 5000
    env_file:
      - ./.env

